---
- hosts: localhost
  tasks: 
  - name: "aaaa"
    shell: echo "{{ item.p1 }} --- {{ item.p2}}" > /tmp/tt.txt
    register: result
    with_items:
      - p1: "{{p1}}"
        p2: "{{p2}}"

  - debug: var=result.stdout_lines
                

    
